// Code generated by protoc-gen-go.
// source: changesource.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	changesource.proto

It has these top-level messages:
	ChangeRequest
	ChangeResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

// Repo type denoting the underlying repo type
type ChangeRequest_RepoType int32

const (
	ChangeRequest_UNKNOWN ChangeRequest_RepoType = 0
	ChangeRequest_GIT     ChangeRequest_RepoType = 1
)

var ChangeRequest_RepoType_name = map[int32]string{
	0: "UNKNOWN",
	1: "GIT",
}
var ChangeRequest_RepoType_value = map[string]int32{
	"UNKNOWN": 0,
	"GIT":     1,
}

func (x ChangeRequest_RepoType) String() string {
	return proto1.EnumName(ChangeRequest_RepoType_name, int32(x))
}

type ChangeRequest struct {
	RepoType ChangeRequest_RepoType `protobuf:"varint,6,opt,name=repo_type,enum=proto.ChangeRequest_RepoType" json:"repo_type,omitempty"`
	// String identifying the project in the master
	Project string `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	// Opaque string identifying this repo (used on the builder to clone/checkout the repo)
	Repo string `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
	// Opaque identifier for a single commit (repo specific)
	Commit string `protobuf:"bytes,3,opt,name=commit" json:"commit,omitempty"`
	// Which branch this commit applies to
	Branch string `protobuf:"bytes,4,opt,name=branch" json:"branch,omitempty"`
	// List of modified paths within the commit
	Files []string `protobuf:"bytes,5,rep,name=files" json:"files,omitempty"`
}

func (m *ChangeRequest) Reset()         { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string { return proto1.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()    {}

type ChangeResponse struct {
}

func (m *ChangeResponse) Reset()         { *m = ChangeResponse{} }
func (m *ChangeResponse) String() string { return proto1.CompactTextString(m) }
func (*ChangeResponse) ProtoMessage()    {}

func init() {
	proto1.RegisterEnum("proto.ChangeRequest_RepoType", ChangeRequest_RepoType_name, ChangeRequest_RepoType_value)
}

// Client API for ChangeSource service

type ChangeSourceClient interface {
	Notify(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeResponse, error)
}

type changeSourceClient struct {
	cc *grpc.ClientConn
}

func NewChangeSourceClient(cc *grpc.ClientConn) ChangeSourceClient {
	return &changeSourceClient{cc}
}

func (c *changeSourceClient) Notify(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeResponse, error) {
	out := new(ChangeResponse)
	err := grpc.Invoke(ctx, "/proto.ChangeSource/Notify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ChangeSource service

type ChangeSourceServer interface {
	Notify(context.Context, *ChangeRequest) (*ChangeResponse, error)
}

func RegisterChangeSourceServer(s *grpc.Server, srv ChangeSourceServer) {
	s.RegisterService(&_ChangeSource_serviceDesc, srv)
}

func _ChangeSource_Notify_Handler(srv interface{}, ctx context.Context, buf []byte) (proto1.Message, error) {
	in := new(ChangeRequest)
	if err := proto1.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(ChangeSourceServer).Notify(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _ChangeSource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChangeSource",
	HandlerType: (*ChangeSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _ChangeSource_Notify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
